### ISSUE TITLE
アプリ起動時にSwiftのコンストラクタでBLEの権限が求められる

### ISSUE THREAD

**Issue by shiron-dev** [after-school-garbage-squad/beacon_plugin#4]
アプリ起動時にFlutter側のPermissionの要求を待たずに勝手にPluginがPermissionの要求を行なってしまう。

Swiftでinit時にBLE周りのインスタンスを初期化しているのが問題なのは把握済み
しかし、これを改善するには現状のコードをそれなりに変える必要があるので保留

**Comment by hidekitux** [comment]
参考になるか分からん↓
https://github.com/pauldemarco/flutter_blue/pull/599
